### ISSUE TITLE
Reading var task fails with long labels

### ISSUE THREAD

**Issue by mas802** [mas802/stata-ux#5]
Under some circumstances the variable describe task will fail and lock the system if variable labels are displayed on multiple lines.

**Comment by wbuchanan** [comment]
You could probably get the same/similar result as the describe command using some of the Java I had written for the [jsonio package](https://github.com/wbuchanan/StataJSON) or from the more generic classes that I spun out of that in [Stata Java Utilities](https://github.com/wbuchanan/StataJavaUtilities).  In particular, you'd want to take a look at the [Meta class object](https://github.com/wbuchanan/StataJavaUtilities/blob/master/src/main/java/org/paces/Stata/MetaData/Meta.java) which reads the metadata out of the file loaded in memory (e.g., var names, var labels, starting/ending indices for observations, total records in the file, value labels, etc...).  It might help with the rendering issues if nothing else.

**Comment by mas802** [comment]
@wbuchanan thanks, that looks very interesting. At the moment I run this without a .jar called from the Stata side. I will see if I should reorganise, might be helpful to have a helper class directly in Java as well.

**Comment by wbuchanan** [comment]
@mas802 Not a problem.  I figured it might come in handy for others.  The version in the repository should be available for use with Maven as well.
